// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX1yiEBusnVKVpUfG4FkO519M7gvx9WZY',
    appId: '1:568207779506:web:db3e081faa9afe45110bab',
    messagingSenderId: '568207779506',
    projectId: 'pi-mobile-62a5a',
    authDomain: 'pi-mobile-62a5a.firebaseapp.com',
    storageBucket: 'pi-mobile-62a5a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPWfL9D-UrILCJo7sKOIMf0UOZIcySwk',
    appId: '1:568207779506:android:8c06beeaf4ea86be110bab',
    messagingSenderId: '568207779506',
    projectId: 'pi-mobile-62a5a',
    storageBucket: 'pi-mobile-62a5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjHTry0mPGp64g8aWL_Jg_LinNc7jkYd0',
    appId: '1:568207779506:ios:571e715f87f5e126110bab',
    messagingSenderId: '568207779506',
    projectId: 'pi-mobile-62a5a',
    storageBucket: 'pi-mobile-62a5a.firebasestorage.app',
    iosBundleId: 'com.example.piprojeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjHTry0mPGp64g8aWL_Jg_LinNc7jkYd0',
    appId: '1:568207779506:ios:571e715f87f5e126110bab',
    messagingSenderId: '568207779506',
    projectId: 'pi-mobile-62a5a',
    storageBucket: 'pi-mobile-62a5a.firebasestorage.app',
    iosBundleId: 'com.example.piprojeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX1yiEBusnVKVpUfG4FkO519M7gvx9WZY',
    appId: '1:568207779506:web:f49a44d93959c0c2110bab',
    messagingSenderId: '568207779506',
    projectId: 'pi-mobile-62a5a',
    authDomain: 'pi-mobile-62a5a.firebaseapp.com',
    storageBucket: 'pi-mobile-62a5a.firebasestorage.app',
  );

}